// Generated by CoffeeScript 2.1.1
// iplotCorr: heatmap of correlation matrix linked to scatterplots
// Karl W Broman
HTMLWidgets.widget({
  name: "iplotCorr",
  type: "output",
  initialize: function(widgetdiv, width, height) {
    if (height > width / 2) {
      // prefer aspect ratio width/height = 2
      height = width / 2;
    }
    d3.select(widgetdiv).append("svg").attr("width", width).attr("height", height).attr("class", "qtlcharts");
    return {
      x: null
    };
  },
  renderValue: function(widgetdiv, x, instance) {
    return this.doRenderValue(widgetdiv, x, instance);
  },
  doRenderValue: function(widgetdiv, x, instance) {
    var chartOpts, height, ref, ref1, ref2, svg, widgetid, width;
    instance.x = x;
    svg = d3.select(widgetdiv).select("svg");
    // clear svg and remove tool tips
    svg.selectAll("*").remove();
    widgetid = d3.select(widgetdiv).attr('id');
    d3.selectAll(`div.d3-tip.${widgetid}`).remove();
    chartOpts = (ref = x.chartOpts) != null ? ref : [];
    width = (ref1 = chartOpts != null ? chartOpts.width : void 0) != null ? ref1 : widgetdiv.clientWidth;
    height = (ref2 = chartOpts != null ? chartOpts.height : void 0) != null ? ref2 : widgetdiv.clientHeight;
    // revise size of svg and div container
    svg.attr("width", width);
    svg.attr("height", height);
    d3.select(widgetdiv).attr("style", `width:${chartOpts.width}px;height:${chartOpts.height}px;`);
    if (x.data.scatterplots) {
      return iplotCorr(widgetdiv, x.data, chartOpts);
    } else {
      return iplotCorr_noscat(widgetdiv, x.data, chartOpts);
    }
  },
  resize: function(widgetdiv, width, height, instance) {
    if (instance.x) {
      return this.doRenderValue(widgetdiv, instance.x, instance);
    }
  }
});
